

services:
  mongodb:
    image: mongo:6
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express
    container_name: mongo_express
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_URL: mongodb://admin:password@mongodb:27017/

  fastapi:
    build: .
    container_name: fastapi_app
    restart: always
    depends_on:
      - mongodb
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://admin:password@mongodb:27017
    volumes:
      - .:/app
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000"

volumes:
  mongo_data:
